"""status history

Revision ID: 4aaa30efd5b7
Revises: 6993e8b94f7f
Create Date: 2026-09-20 21:40:17.099912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4aaa30efd5b7'
down_revision: Union[str, None] = '6993e8b94f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statushistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statushistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statushistory_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_statushistory_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statushistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statushistory_job_id'))
        batch_op.drop_index(batch_op.f('ix_statushistory_changed_at'))

    op.drop_table('statushistory')
    # ### end Alembic commands ###
