"""init schema

Revision ID: 6993e8b94f7f
Revises: 
Create Date: 2026-09-19 21:41:01.726377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6993e8b94f7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('licences', sa.JSON(), nullable=True),
    sa.Column('sample_letters', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('API', 'SCRAPE', 'IMAP', name='sourcekind'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_name'), ['name'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sa.Enum('P1_IDF', 'P2_FRONTALIER', 'P3_FRANCE', 'P4_SUISSE', 'UNKNOWN', name='zone'), nullable=False),
    sa.Column('metier', sa.Enum('SUPPORT', 'LIVREUR', 'POLYVALENT', 'AUTRE', name='metier'), nullable=False),
    sa.Column('contract_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('dedup_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DRAFTED', 'APPLIED', 'FOLLOWED_UP', 'INTERVIEW', 'REJECTED', 'IGNORED', name='jobstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_job_dedup_hash')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_metier'), ['metier'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title_normalized'), ['title_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_zone'), ['zone'], unique=False)

    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_job_id'))
        batch_op.drop_index(batch_op.f('ix_application_is_current'))

    op.drop_table('application')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_zone'))
        batch_op.drop_index(batch_op.f('ix_job_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_source_id'))
        batch_op.drop_index(batch_op.f('ix_job_score'))
        batch_op.drop_index(batch_op.f('ix_job_published_at'))
        batch_op.drop_index(batch_op.f('ix_job_metier'))
        batch_op.drop_index(batch_op.f('ix_job_external_id'))
        batch_op.drop_index(batch_op.f('ix_job_dedup_hash'))

    op.drop_table('job')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_name'))

    op.drop_table('source')
    op.drop_table('profile')
    # ### end Alembic commands ###
